### ISSUE TITLE
Dynamically replacing background image in ProfilePageHeader renders a blurry image. 

### ISSUE THREAD

**Issue by chrisjakuta** [creativetimofficial/now-ui-kit-react#1]
When I try to dynamically replace the background image in `ProfilePageHeader` the image is always blurry, this is also true for images that are already in the public folder. 

Here is a snippet of the changes =>

`<div
          className="page-header-image"
          style={{
            backgroundImage: props.data.blog_picture_context
          }}
          ref={pageHeader}
        ></div>`

This will simply render a blurry image, please let me know if I need to post more of the code as a point of reference.

**Comment by chrisjakuta** [comment]
<img width="1552" alt="Screen Shot 2020-02-15 at 10 57 25 AM" src="https://user-images.githubusercontent.com/30093831/74591985-79a0b580-4fe2-11ea-9cb5-30f76b9d462e.png">

**Comment by chrisjakuta** [comment]
Solved !! 

Here is what I was doing wrong. Perhaps someone will need this. 
Instead of =>

`backgroundImage : props.data.blog_picture_context`

Use => 

`backgroundImage : 'url(' + props.data.blog_picture_context + ')'`

Works perfectly !!

**Comment by einazare** [comment]
Hello there, @chrisjakuta ,

Sorry for not responding sooner, this is a free product, and beside that, the issue was opened on a weekend day, we do not work on weekends.

Glad everything works now.

Happy Hacking!

Best,
Manu
