### ISSUE TITLE
[Bug] npm install returns error: unable to resolve dependency tree

### ISSUE THREAD

**Issue by FatihBekdemir** [creativetimofficial/now-ui-kit-react#11]
### Version
1.5.1
### Reproduction link
https://github.com/creativetimofficial/now-ui-kit-react
### Operating System
Windows
### Device
Lenovo
### Browser & Version
Chrome
### Steps to reproduce
1. Clone the now-ui-kit-react repo from github page, or from the https://www.creative-tim.com/product/now-ui-kit-react page.
2. Open a terminal where the project folder is located.
3. run npm install
### What is expected?
It should start loading node_modules folder with the expected modules inside.
### What is actually happening?
It returns the error below:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: now-ui-kit-react@1.5.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0 || ^17.0.0" from react-datetime@3.1.1
npm ERR! node_modules/react-datetime
npm ERR!   react-datetime@"3.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\X\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\X\AppData\Local\npm-cache\_logs\2022-08-04T12_31_35_183Z-debug-0.log

---
### Solution
First, running this command:
=> npm install --legacy-peer-deps
Then, normal npm install
=> npm install

it will give you this response:
added 1810 packages, and audited 1811 packages in 4m
209 packages are looking for funding
  run `npm fund` for details
12 high severity vulnerabilities

=> npm start

**Comment by sajadevo** [comment]
This issue is fixed on v1.5.2.
